# This gitHub Actions workflow. will destroy all the resources such as S3 bucket, role, policy,
# which is shared between different stages such as prod/dev
# Make sure you have deleted all the resources of dev and prod stages before executing this one.
name: 'Terraform Destroy Shared Resources at different stages'

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  destroy_with_terraform:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform/shared

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Clone your repo code
      uses: actions/checkout@v4

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
          terraform_version: '1.12.2'

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init

    - name: Terraform destroy
      run: terraform destroy --auto-approve
